#!/bin/bash

for a in 02 03 04 05 06 07 08 09 10 11 12 13 14; do
  PROJECT=ad-training-${a}
  mkdir ${PROJECT}
  pushd ${PROJECT}

  echo 'export BBL_IAAS=gcp' > .envrc
  echo "export BBL_ENV_NAME=${PROJECT}" >> .envrc
  echo 'export BBL_GCP_SERVICE_ACCOUNT_KEY="../bosh.key.json"' >> .envrc
  echo 'export BBL_GCP_REGION="us-east4"' >> .envrc
  echo 'eval "$(bbl print-env)"' >> .envrc
  echo 'eval "$(bucc/bin/bucc env)"' >>.envrc
  source .envrc

  bbl plan -lb-type concourse

  ln -s ../bucc/
  ln -s bucc/bbl/*-director-override.sh .
  cd terraform
  ln -s ../bucc/bbl/terraform/$BBL_IAAS/* .
  popd
done
