concourse_lb_ip: 35.221.50.242
concourse_target_pool: ad-training-02-concourse
director__concourse_domain: 35.221.50.242
director__internal_ip: 10.0.0.6
director__tags:
- ad-training-02-bosh-director
- ad-training-02-concourse-open
- concourse
director__target_pool: ad-training-02-concourse
director_address: https://35.221.28.195:25555
director_name: bosh-ad-training-02
external_ip: 35.221.28.195
internal_cidr: 10.0.0.0/16
internal_gw: 10.0.0.1
internal_tag_name: ad-training-02-internal
jumpbox__internal_ip: 10.0.0.5
jumpbox__tags:
- ad-training-02-bosh-open
- ad-training-02-jumpbox
jumpbox_url: 35.221.28.195:22
network: ad-training-02-network
subnetwork: ad-training-02-subnet
subnetwork_reserved_ips: 10.0.0.1-10.0.0.255
subnetwork_static_ips: 10.0.255.0-10.0.255.254
